### PR TITLE
fixed jdk8 (1.8.0_05-b13) install on Mac OS X (10.10.2)

### PR DESCRIPTION
**Pull request by mzipay**
I tried to run "mvn -Pjdk8 -Dgpg.skip=true clean install" from the docs so that I could use 2.5-SNAPSHOT after discovering that my tests no longer ran on one of my projects.

However, this failed with:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project uispec4j: Compilation failure
[ERROR] /private/tmp/UISpec4J/uispec4j/src/main/java-jdk8/org/uispec4j/interception/toolkit/ToolkitDelegate.java:[131,19] error: cannot find symbol

Looking into this, I discovered that the SunToolkit#getDataTransferer() method being called from ToolkitDelegate#getDataTransferer() does not exist. I did find a similar method, SunToolkit#getDataTransfererClassName(), and was able to finally get the JDK8 install for UISpec4J working successfully with the change in this pull request.

Thanks.

### CODE REVIEW

**Comment by nebulorum** [comment]
I can build on 1.8.0_31-b13 clean on my Mac 10.10.2. Do you need that specific version of the JDK?

Also I have pushed 2.5-RC1 to Maven Central. Can you try with the built artifacts would love to have more input.

**Comment by mzipay** [comment]
Hi, I saw RC1 out on mvnrepository.com last night and tried it out. It gets me further, but now I'm facing an issue (whether I use RC1 or my patched SNAPSHOT) where the application window never comes up and the window interceptor timeout expires, regardless of how high I set it.

I have a Win7 vm that I'll try to run my test suite on, just to confirm this is something Mac-specific (which I believe is the case at this time). Regardless, tonight I discovered that my pull request has a bug, so please just reject it.

I *can* confirm that the SunToolkit#getDataTransferer() method (which is called from uispec4j.interception.toolkit.ToolkitDelegate#getDataTransferer()) does not exist in the Oracle JDK8 for Mac OS X. But I need to do some further testing with the available SunToolkit#getDataTransfererClassName(). I can't call newInstance() on the reflected class (private constructor - odd this didn't show up in my earlier tests), but instead need to call getInstanceImpl().

**Comment by nebulorum** [comment]
Ok I'll close this one. 2.5-RC1 code is in my repo and pull request  
https://github.com/UISpec4J/UISpec4J/pull/16.

I would like to carry this is an issue and seeif we can fix it on that pull request. I know it may be a tall order but if you can come up with a test that fails and can be placed on the issue it would be great. RC1 has some flaky behavior and I'm still trying to make sure nothing is wrong.

As for the Oracle JDK 8 on a Mac 10.2.2:

```
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

And on this version I have no problem building and the getDataTransferer is there on the SunToolkit. Can you build on a newer JDK?

**Comment by mzipay** [comment]
I updated my Oracle JDK 8:
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

But still getting the window interceptor timeout.  Maybe this is just user error??

Here's the test case I'm running:

```java
public class UISpec4JPull17 {
    UISpec4JPull17() {
        JFrame frame = new JFrame("UISpec4JPull17");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new JButton("TEST"));
        frame.pack();
        frame.setVisible(true);
    }

    public static void main(String[] args) throws Exception {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UISpec4JPull17();
            }
        });
    }
}
```

```java
public class UISpec4JPull17Test extends UISpecTestCase {
    @Before
    @Override
    public void setUp() throws Exception {
        super.setUp();
        setAdapter(new MainClassAdapter(UISpec4JPull17.class, new String[0]));
    }

    @Test
    public void testButton() {
        getMainWindow().getButton().textEquals("TEST");
    }
}
```

If I `@Ignore` the test case, everything's fine, and the app runs as expected. But if the test case is allowed to run, `mvn package` fails:

testButton(net.ninthtest.UISpec4JPull17Test)  Time elapsed: 10.035 sec  <<< FAILURE!
java.lang.AssertionError: No window was shown (timeout expired)

I thought that maybe SwingUtilities#invokeLater might be the problem, but I still get the failure even when not using it.

**Comment by nebulorum** [comment]
Thank for the test. It is really interesting. I added it to the UISpec4J project. If you you run it via Maven surefire it works fine. If I run on the IntelliJ it fails. Worst several tests are failing on IntelliJ on Pull 16. However they pass on the current master. I'll investigate some more.

**Comment by mzipay** [comment]
Ok, just want to clarify my results:
(1) If I run my test against 2.5-RC1, then it fails regardless of JDK (timeout expired).
(2) If I attempt to build using JDK 1.8.0_05-b13, the build fails (SuntToolkit#getDataTransferer does not exist).
(3) But if I run it against a 2.5-SNAPSHOT that I built with the updated JDK 1.8.0_40-b27, then it passes via Maven surefire.

So for now I will use the rebuilt 2.5-SNAPSHOT. If I run into anything else of interest while testing this, I will update here. Thanks for your assistance!

**Comment by nebulorum** [comment]
Ok. I still want to get this sorted out since this is related to moving the test to JUnit4. Somethings is not right. I may rollback the entire thing.

**Comment by nebulorum** [comment]
After battling a bit with errors, I did a clean rebuild and everything passed. Then I did a new Maven project and got the failure. But  was caused by not having the correct classifier.

With this dependency (with *classifier*) it builds clean:
```
<dependency>
      <groupId>org.uispec4j</groupId>
      <artifactId>uispec4j</artifactId>
      <version>2.5-RC1</version>
      <classifier>jdk8</classifier>
      <scope>test</scope>
    </dependency>
```

Can you try that?

**Comment by mzipay** [comment]
I tried it, but it didn't seem to have any effect. My test case still failed with the window timeout.

But then I refactored my test case:
1. Do *not* extend UISpecTestCase. (Instead, do UISpec4J.init() in a `@BeforeClass` method, and also set the window intercept timeout *very* high - it's at 79s now.)
2. Go back to using the rebuilt 2.5-SNAPSHOT, but also use <classifier>jdk8</classifier>.

This was SUCCESSFUL, though it takes a really long time for the test case to complete. I'm going to try to profile it to see where it's hanging.

**Comment by nebulorum** [comment]
I'm really intrigued. I'm using your code on JDK 1.8.0_40 and Mac 10.2.2. Here are my dependencies:

org.uispec4j:uispec4j:jar:jdk8:2.5-RC1:test
org.hamcrest:hamcrest-core:jar:1.3:test
junit:junit:jar:4.12:test

Works like a charm. I you want I may put this test project somewhere.

**Comment by mzipay** [comment]
My dependencies are almost identical -
org.uispec4j:uispec4j:jar:jdk8:2.5-SNAPSHOT:test
org.hamcrest:hamcrest-core:jar:1.3:test
junit:junit:jar:4.12:test

By all means, use the test project however you see fit. Again, thanks for your time.

**Comment by nebulorum** [comment]
Added this Gist with the project https://gist.github.com/nebulorum/0015cf142cea80739e55

If you can discover how to cause the issue on 2.5-RC1 I would greatly appriciate. 

I managed to fix the problem on building on JDK8 40, I hope. There was a problem in sequencing Modal dialogs. You have to create the modal dialog on the EDT thread or depending on the sequencing the secondary event loop gets lost.

**Comment by mzipay** [comment]
I am able to reproduce the window timeout issue consistently when using SwingUtilities#invokeLater (regardless of how high the window intercept timeout is set).

If I use SwingUtilities#invokeAndWait (or just instantiate my JFrame without using SwingUtilities at all), then it works fine.  I suspect the issue may be related to intercepting on the EDT, but I'm not knowledgeable enough in that area to really troubleshoot it.

**Comment by nebulorum** [comment]
Can you give me the gist or code that caused the failure?

**Comment by mzipay** [comment]
Sure, here is the actual project source: https://bitbucket.org/mzipay/character-encoding-translator/src/2.0.1/src/main/java/net/ninthtest/CharacterEncodingTranslator.java
